### ISSUE TITLE
br.gov.frameworkdemoiselle.behave.exception.BehaveException: Limpeza de campo não concluída com sucesso

### ISSUE THREAD

**Issue by mestihudson** [demoiselle/behave#189]
Estou executando o seguinte cenário:

``` cucumber
Cenário: Solicitar registro de responsável pela unidade

Dado que vou para a tela "Inicial"
Então será exibido "Bem-te-vi Autenticar Usuário"
Quando clico em "Registro de Responsável"
Dado que estou na tela "Confirmar Ciência de Responsabilidade pela Unidade"
Quando seleciono a opção "Concordo com o termo de responsabilidade"
Quando informo "88558983100" no campo "CPF do Responsável"
Quando informo "abcde" no campo "Captcha"
Quando clico em "Confirmar Ciência"
Então será exibido "Mensagem de Texto"
```

e o passo:

``` cucumber
Quando informo "88558983100" no campo "CPF do Responsável"
```

está apresentando o erro informado no título do tópico.

Segue a stack completa:

```
84571713304@serpro-1552224:~/Workspaces/dominios/sigdom-test$ clear;mvn -q clean test

[debug] execute contextualize
[debug] execute contextualize

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running br.gov.serpro.dominios.test.DominiosTest
08:32:34,604 INFO  (main) [BehaveContext]: --------------------------------
08:32:34,604 INFO  (main) [BehaveContext]: Demoiselle Behave Iniciado
08:32:34,605 INFO  (main) [BehaveContext]: --------------------------------
08:32:34,652 INFO  (main) [JBehaveParser]: Configurando Parser JBehave...
08:32:34,665 INFO  (main) [JBehaveParser]: Iniciando Parser JBehave...
08:32:34,665 INFO  (main) [JBehaveParser]: Executando história: [[stories/solicitacao.storyConverted]]
Processing system properties {}
Using controls EmbedderControls[batch=false,skip=false,generateViewAfterStories=true,ignoreFailureInStories=true,ignoreFailureInView=true,verboseFailures=true,verboseFiltering=false,storyTimeoutInSecs=3600,threads=1]

(BeforeStories)
08:32:34,752 INFO  (main) [BeforeAfterSteps]: 


08:32:34,752 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Running story stories/solicitacao.storyConverted
Funcionalidade: Solicitacao
(stories/solicitacao.storyConverted)
Scenario: Solicitar registro de responsável pela unidade
Dado que vou para a tela "Inicial"
Então será exibido "Bem-te-vi Autenticar Usuário"
Quando clico em "Registro de Responsável"
Dado que estou na tela "Confirmar Ciência de Responsabilidade pela Unidade"
Quando seleciono a opção "Concordo com o termo de responsabilidade"
Quando informo "88558983100" no campo "CPF do Responsável" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
08:32:54,979 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [http://localhost:8080/bemtevi/public/pages/security/login.jsf] salvo em [/home/84571713304/Workspaces/dominios/sigdom-test/target/jbehave/view/screenshots/failed-scenario-c9fe8caf-2c95-415d-bbe1-a992b20a0dc8.png] com [157.034] bytes
Quando informo "abcde" no campo "Captcha" (NOT PERFORMED)
Quando clico em "Confirmar Ciência" (NOT PERFORMED)
Então será exibido "Mensagem de Texto" (NOT PERFORMED)


Failed to run story stories/solicitacao.storyConverted
java.lang.reflect.UndeclaredThrowableException
    at com.sun.proxy.$Proxy16.sendKeys(Unknown Source)
    at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.inform(CommonSteps.java:207)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
    at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
    at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
    at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:443)
    at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
    at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
    at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
    ... 19 more
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Limpeza de campo não concluída com sucesso
    at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebTextField.sendKeysWithTries(WebTextField.java:90)
    at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebTextField.sendKeys(WebTextField.java:53)
    ... 24 more

(AfterStories)
08:32:55,243 INFO  (main) [BeforeAfterSteps]: >>Finalizando Aplicação<<

Generating reports view to '/home/84571713304/Workspaces/dominios/sigdom-test/target/jbehave' using formats '[defaultstoryreport, console, html, stats]' and view properties '{defaultFormats=stats, decorateNonHtml=true, viewDirectory=view, decorated=ftl/jbehave-report-decorated.ftl, reports=ftl/jbehave-reports-with-totals.ftl, maps=ftl/jbehave-maps.ftl, navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl}'
Reports view generated with 1 stories (of which 0 pending) containing 1 scenarios (of which 0 pending)
Failures in reports view: 1 scenarios failed
08:32:55,472 INFO  (main) [JBehaveParser]: Finalizando Parser JBehave...
08:32:55,472 INFO  (main) [BehaveContext]: --------------------------------
08:32:55,472 INFO  (main) [BehaveContext]: Demoiselle Behave Finalizado
08:32:55,472 INFO  (main) [BehaveContext]: --------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 21.126 sec <<< FAILURE!
testAllStories(br.gov.serpro.dominios.test.DominiosTest)  Time elapsed: 21.099 sec  <<< FAILURE!
java.lang.AssertionError: Passo com falha: [Quando informo "88558983100" no campo "CPF do Responsável"] causa: Quando informo "88558983100" no campo "CPF do Responsável"
    at org.junit.Assert.fail(Assert.java:91)
    at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:125)
    at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:143)
    at br.gov.serpro.dominios.test.DominiosTest.testAllStories(DominiosTest.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.runners.BlockJUnit4ClassRunner.runNotIgnored(BlockJUnit4ClassRunner.java:79)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:71)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:49)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testAllStories(br.gov.serpro.dominios.test.DominiosTest): Passo com falha: [Quando informo "88558983100" no campo "CPF do Responsável"] causa: Quando informo "88558983100" no campo "CPF do Responsável"

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project sigdom-test: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/84571713304/Workspaces/dominios/sigdom-test/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by daaneto** [comment]
Também estou tendo o mesmo problema relatado na questão inicial. O valor sendo passado está mascarado. Também testei sem a máscara, mas não funcionou. Durante a execução, o behave faz diversas tentativas até lançar o erro. Estou usando a versão mais recente: 1.5.1
