### ISSUE TITLE
Erro na integração com ALM

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#235]
> Erro:

16:44:19,502 DEBUG (pool-1-thread-1) [ALMIntegration]: Acessando ao autenticador ALM
16:44:19,550 DEBUG (pool-1-thread-1) [ALMIntegration]: ------------- Integração ALM Iniciada -------------

16:44:19,555 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [0000000000]
16:44:20,217 DEBUG (pool-1-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-processo+%28Gerenciamento+de+Qualidade%29/testplan/urn:com.ibm.rqm:testplan:1825
16:44:20,682 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [0000000000]
16:44:21,070 DEBUG (pool-1-thread-1) [ALMIntegration]: Enviando Caso de Teste:

16:44:21,111 DEBUG (pool-1-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-processo+%28Gerenciamento+de+Qualidade%29/testcase/testcaseAceitaromodopadraodeconfiguracaodefiltrosdeunidade
16:44:21,111 DEBUG (pool-1-thread-1) [ALMIntegration]: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Aceitar o modo padrão de configuração de filtros de unidade</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que estou logado com usuário "beraldo"&lt;br/&gt;Dado que a configuração estabelecida previamente para o Tipo de Unidade "ALF", Unidade "ALF/AERBLE" seja: 
|palavras_chave                          |ordenacao_processos  |
|CPF Responsável Atual, Data do Protocolo|Data do Protocolo    |&lt;br/&gt;Quando vou para a tela "Criar Filtro de Unidade"&lt;br/&gt;Quando informo "ALF" no campo "Tipo de Unidade"&lt;br/&gt;Quando informo "ALF/AERBLE" no campo "Unidade"&lt;br/&gt;Então será exibido na "Palavra-Chave de Exibição" exatamente os valores "CPF Responsável Atual, Data do Protocolo"&lt;br/&gt;Então será exibido na "Ordenação dos Processos" exatamente os valores "Data do Protocolo"&lt;br/&gt;Quando clico em "Confirmar"&lt;br/&gt;Então será exibido na caixa de diálogo "A operação no filtro ALF/AERBLE foi confirmada com sucesso."&lt;br/&gt;E confirmo a caixa de diálogo</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>
```
16:44:21,492 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
16:44:21,854 DEBUG (pool-1-thread-1) [ALMIntegration]: Enviando Plano de Teste:

16:44:21,861 DEBUG (pool-1-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-processo+%28Gerenciamento+de+Qualidade%29/testplan/urn:com.ibm.rqm:testplan:1825
16:44:21,861 DEBUG (pool-1-thread-1) [ALMIntegration]: 

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<testplan xmlns="http://jazz.net/xmlns/alm/qm/v0.1/">
    <testcase href="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-processo+%28Gerenciamento+de+Qualidade%29/testcase/testcaseAceitaromodopadraodeconfiguracaodefiltrosdeunidade"/>
</testplan>
```

16:44:22,375 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao enviar Plano de Teste [HTTP/1.1 500 Internal Server Error]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:247)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:100)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:125)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao enviar Plano de Teste [HTTP/1.1 500 Internal Server Error]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:186)
	... 12 more

> Configuração:

SO: Windows 7 64 bits
Navegador: IE9
DBehave: 1.3.2-SNAPSHOT
Java: jre 7 up 65
Eclipse: Kepler Service Release 1
behave.integration.alm.url.security: https://alm.serpro/qm/j_security_check
behave.integration.alm.url.services: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/
behave.integration.alm.projectArea: e-processo+%28Gerenciamento+de+Qualidade%29
behave.integration.alm.testPlanId: 1825
behave.integration.authenticator.host: localhost
behave.integration.authenticator.port: 9990

> Observações:

Já mudei a propriedade "behave.integration.alm.projectArea" para "e-Processo (Gerenciamento de Qualidade)" e ocorre outro erro:

17:11:49,332 DEBUG (pool-1-thread-1) [ALMIntegration]: Acessando ao autenticador ALM
17:11:49,370 DEBUG (pool-1-thread-1) [ALMIntegration]: ------------- IntegraÃ§Ã£o ALM Iniciada -------------

17:11:49,377 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [0000000000]
17:11:50,119 DEBUG (pool-1-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-Processo+%28Gerenciamento+de+Qualidade%29/testplan/urn:com.ibm.rqm:testplan:1825
17:11:50,598 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Plano de teste [1825] não encontrado na área de projeto [e-Processo+%28Gerenciamento+de+Qualidade%29]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:247)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:100)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:125)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Plano de teste [1825] não encontrado na área de projeto [e-Processo+%28Gerenciamento+de+Qualidade%29]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:156)
	... 12 more

**Comment by rogernobre** [comment]
Mesmo com a propriedade "behave.integration.alm.autoAssociateTestCaseInPlan=false" e sem link para requisito, está dando erro ao enviar caso de testes: 

18:03:16,060 DEBUG (pool-4-thread-1) [ALMIntegration]: Acessando ao autenticador ALM
18:03:16,068 DEBUG (pool-4-thread-1) [ALMIntegration]: ------------- IntegraÃ§Ã£o ALM Iniciada -------------

18:03:16,068 DEBUG (pool-4-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
18:03:16,544 DEBUG (pool-4-thread-1) [ALMIntegration]: Enviando Caso de Teste:

18:03:16,551 DEBUG (pool-4-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-Processo+%28Gerenciamento+de+Qualidade%29/testcase/testcaseNovousuarioacessaatela(criteriospadroes)
18:03:16,551 DEBUG (pool-4-thread-1) [ALMIntegration]: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Novo usuário acessa a tela (critérios padrões)</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Consultar Processo Java&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores: &lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|&lt;br/&gt;Quando informo &amp;#34;N&amp;#250;mero Ac&amp;#243;rd&amp;#227;o DRJ&amp;#34; no campo &amp;#34;Selecionar palavra-chave&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores:&lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|&lt;br/&gt;|starCinza.png.jsf N&amp;#250;mero Ac&amp;#243;rd&amp;#227;o DRJ|&lt;br/&gt;Quando vou para a tela &amp;#34;Consultar Processo Java&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores:&lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>

18:03:17,090 ERROR (pool-4-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:159)
	... 13 more

Isto também está sendo resolvido ou já é outra coisa?

**Comment by juliancesar** [comment]
@rogernobre, peço que abra uma issue separada para este caso, pois aparentemente parece ser outro problema.
Obrigado.

**Comment by rogernobre** [comment]
@juliancesar, aberta a issue https://github.com/demoiselle/behave/issues/303.

Valeu.

**Comment by juliancesar** [comment]
Este problema foi corrigido na nova versão da **ALM (5.0.2)** colocada em produção neste final de semana (01/02/2015) dentro do Serpro.
Favor validar.

**Comment by rogernobre** [comment]
Validado.
