### ISSUE TITLE
Erro de 'exception-record-id-not-found' no conjunto de dados de teste

### ISSUE THREAD

**Issue by rogerritter** [demoiselle/behave#302]
Olá Pessoal,

No modelo de conjunto de dados http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-dados.html estou obtendo o seguinte erro:

<hr>
18:07:42,281 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
log4j:WARN No appenders could be found for logger (org.apache.http.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Running story stories\Anunciar\Anunciar_Acessos.storyConverted
Funcionalidade: Acessos
(stories\Anunciar\Anunciar_Acessos.storyConverted)
Narrative:
In order to acesso a minha área
As a usuario
I want to recuperar meu usuário
Scenario: adiciono a obra
Dado que estou na tela "Tela Inicial"
18:07:50,547 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [about:blank] salvo em [failed-scenario-c4d7d28b-2cb7-4219-a955-37d77dce99ac.png] com [3.871] bytes
Quando seleciono "{obra}" do conjunto de dados "obras" (FAILED)
(java.lang.IllegalArgumentException: can't parse argument number: exception-record-id-not-found)
Quando informo o valor do campo "Nome Obra" (NOT PERFORMED)
Quando informo o valor do campo "Valor" (NOT PERFORMED)
Quando informo o valor do campo "Prazo" (NOT PERFORMED)
Quando clico em "Inserir" (NOT PERFORMED)

Failed to run story stories\Anunciar\Anunciar_Acessos.storyConverted
java.lang.IllegalArgumentException: can't parse argument number: exception-record-id-not-found
	at java.text.MessageFormat.makeFormat(Unknown Source)
	at java.text.MessageFormat.applyPattern(Unknown Source)
	at java.text.MessageFormat.<init>(Unknown Source)
	at java.text.MessageFormat.format(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.message.BehaveMessage.getString(BehaveMessage.java:75)
	at br.gov.frameworkdemoiselle.behave.internal.dataprovider.DefaultDatasetProvider.findDataRecord(DefaultDatasetProvider.java:55)
	at br.gov.frameworkdemoiselle.behave.internal.dataprovider.DefaultDatasetProvider.setDataProviderCurrentRecord(DefaultDatasetProvider.java:46)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.putRecordIntoDataProvider(CommonSteps.java:406)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:443)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "exception-record-id-not-found"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	... 25 more
<hr>

<b>Nota</b>
- O arquivo parece ser encontrado!
- Se em cenário inserir conforme no exemplo "Cenário: adiciono a obra "{obra}"" a story não é interpretada.
- Win 8, x64.

(Senão for o local de postar este tipo de problema, por favor me orientem)

**Comment by juliancesar** [comment]
@rogerritter, é aqui sim o local apropriado.

@antonioclaudioneiva, você poderia nos ajudar?

**Comment by juliancesar** [comment]
@rogerritter, infelizmente não conseguimos dar atenção a esta questão! Você conseguiu avançar? Ainda precisa de ajuda?

**Comment by juliancesar** [comment]
Issue fechada por falta de retorno. 
Caso o problema ainda ocorra, favor reabrir.
