### ISSUE TITLE
Erro na integração com o ALM - 400 Bad Request

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#303]
Mesmo com a propriedade "behave.integration.alm.autoAssociateTestCaseInPlan=false" e sem link para requisito, está dando erro ao enviar caso de testes: 

18:03:16,060 DEBUG (pool-4-thread-1) [ALMIntegration]: Acessando ao autenticador ALM
18:03:16,068 DEBUG (pool-4-thread-1) [ALMIntegration]: ------------- IntegraÃ§Ã£o ALM Iniciada -------------

18:03:16,068 DEBUG (pool-4-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
18:03:16,544 DEBUG (pool-4-thread-1) [ALMIntegration]: Enviando Caso de Teste:

18:03:16,551 DEBUG (pool-4-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-Processo+%28Gerenciamento+de+Qualidade%29/testcase/testcaseNovousuarioacessaatela(criteriospadroes)
18:03:16,551 DEBUG (pool-4-thread-1) [ALMIntegration]: 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Novo usuário acessa a tela (critérios padrões)</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Consultar Processo Java&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores: &lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|&lt;br/&gt;Quando informo &amp;#34;N&amp;#250;mero Ac&amp;#243;rd&amp;#227;o DRJ&amp;#34; no campo &amp;#34;Selecionar palavra-chave&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores:&lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|&lt;br/&gt;|starCinza.png.jsf N&amp;#250;mero Ac&amp;#243;rd&amp;#227;o DRJ|&lt;br/&gt;Quando vou para a tela &amp;#34;Consultar Processo Java&amp;#34;&lt;br/&gt;Ent&amp;#227;o ser&amp;#225; exibido na tabela &amp;#34;Filtro de pesquisa&amp;#34; os valores:&lt;br/&gt;|Palavra-Chave|&lt;br/&gt;|star.png.jsf CPF Respons&amp;#225;vel Atual|&lt;br/&gt;|star.png.jsf Data do Protocolo|&lt;br/&gt;|star.png.jsf NI Contribuinte|&lt;br/&gt;|star.png.jsf Unidade Atual, Equipe Atual e/ou Atividade Atual|&lt;br/&gt;|star.png.jsf N&amp;#250;mero de Inscri&amp;#231;&amp;#227;o|&lt;br/&gt;|star.png.jsf N&amp;#250;mero Processo|</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>
```

18:03:17,090 ERROR (pool-4-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:159)
	... 13 more

Pensei primeiramente que fosse o erro da issue https://github.com/demoiselle/behave/issues/235 mas parece que é outro.

Alguém mais está tendo este erro?

Estou usando a versão:
Demoiselle Behave 1.4.1-SNAPSHOT em: 12/01/2015 09:48

**Comment by juliancesar** [comment]
@rogernobre, faça um teste para mim, retire o texto do **Design do Caso de Teste** e rode novamente, se funcionar o problema esta em algum caractere especial que não estamos tratando, posso gerar uma SNAPSHOT hoje para corrigir.

**Comment by rogernobre** [comment]
Só uma duvida, essas propriedades abaixo estão corretas:

behave.integration.alm.url.security=https://alm.serpro/qm/j_security_check
behave.integration.alm.url.services=https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/

Estou tendo o seguinte erro agora:

19:10:02,661 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: Autenticador inacessível. Verifique se o processo foi iniciado
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:250)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.RuntimeException: Erro ao enviar mensagem.
	at br.gov.frameworkdemoiselle.behave.integration.alm.autenticator.AutenticatorClient.sendMessage(AutenticatorClient.java:108)
	at br.gov.frameworkdemoiselle.behave.integration.alm.autenticator.AutenticatorClient.open(AutenticatorClient.java:58)
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:112)
	... 13 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.PlainSocketImpl.doConnect(PlainSocketImpl.java:351)
	at java.net.PlainSocketImpl.connectToAddress(PlainSocketImpl.java:213)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:200)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:366)
	at java.net.Socket.connect(Socket.java:529)
	at java.net.Socket.connect(Socket.java:478)
	at java.net.Socket.<init>(Socket.java:375)
	at java.net.Socket.<init>(Socket.java:189)
	at br.gov.frameworkdemoiselle.behave.integration.alm.autenticator.AutenticatorClient.sendMessage(AutenticatorClient.java:96)
	... 15 more

**Comment by juliancesar** [comment]
Acredito que as propriedades estão certas.
Com relação ao erro, é necessário iniciar o __autenticador__ conforme o link abaixo.
http://demoiselle.sourceforge.net/docs/components/behave/reference/lastversion/html/behave-configuracao.html#d0e1539

**Comment by rogernobre** [comment]
Historia:

Cenário: Realizar login no e-Processo Java
Dado que vou para a tela "Login Java"

Xml gerado:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Realizar login no e-Processo Java</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Login Java&amp;#34;</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>

**Comment by juliancesar** [comment]
Funcionou?

**Comment by rogernobre** [comment]
Nops:

19:19:40,009 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:159)
	... 13 more

**Comment by juliancesar** [comment]
Vamos ter que depurar com calma! Amanhã conversamos.

**Comment by rogernobre** [comment]
Ok.

**Comment by rogernobre** [comment]
Testei em homologação (homalm.serpro) e continua a mesma coisa:

11:04:51,234 DEBUG (pool-1-thread-1) [ALMIntegration]: Acessando ao autenticador ALM
11:05:09,890 DEBUG (pool-1-thread-1) [ALMIntegration]: ------------- IntegraÃ§Ã£o ALM Iniciada -------------

11:05:12,395 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
11:05:19,787 DEBUG (pool-1-thread-1) [ALMIntegration]: Enviando Caso de Teste:

11:05:43,563 DEBUG (pool-1-thread-1) [ALMIntegration]: https://homalm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/Demoiselle+Behave+%28Gerenciamento+de+Qualidade%29/testcase/testcaseRealizarloginnoeProcessoJava
11:05:43,568 DEBUG (pool-1-thread-1) [ALMIntegration]: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Realizar login no eProcesso Java</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://homalm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Login Java&amp;#34;</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>

11:05:48,643 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:159)
	... 13 more

**Comment by rogernobre** [comment]
Mudei para a versão 1.4.0 do DBehave e o erro continua:

11:11:24,540 DEBUG (pool-1-thread-1) [ALMIntegration]: https://homalm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/Demoiselle+Behave+%28Gerenciamento+de+Qualidade%29/testcase/testcaseRealizarloginnoeProcessoJava
11:11:24,543 DEBUG (pool-1-thread-1) [ALMIntegration]: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Realizar login no eProcesso Java</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://homalm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Login Java&amp;#34;</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>

11:11:42,213 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:125)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:158)
	... 13 more

**Comment by rogernobre** [comment]
Mudei para a versão 1.3.2 do DBehave e o erro mudou:

11:15:58,930 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
11:15:59,607 DEBUG (pool-1-thread-1) [ALMIntegration]: https://homalm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/Demoiselle+Behave+%28Gerenciamento+de+Qualidade%29/testplan/urn:com.ibm.rqm:testplan:1132
11:15:59,963 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Plano de teste [1132] não encontrado na área de projeto [Demoiselle+Behave+%28Gerenciamento+de+Qualidade%29]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:247)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:100)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:125)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Plano de teste [1132] não encontrado na área de projeto [Demoiselle+Behave+%28Gerenciamento+de+Qualidade%29]
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:156)
	... 13 more

**Comment by rogernobre** [comment]
Mas o trecho interno:

HttpResponse responseTestPlanGet = getRequest(client, "testplan", testPlanNameId);

tem como retorno (responseTestPlanGet.getStatusLine()) igual a "HTTP/1.1 400 Bad Request"

**Comment by rogernobre** [comment]
Os erros continuam mesmo na nova versão do ALM:

14:46:13,964 DEBUG (pool-1-thread-1) [ALMIntegration]: Autenticando usuário [01069360503]
14:46:14,801 DEBUG (pool-1-thread-1) [ALMIntegration]: Enviando Caso de Teste:

14:46:14,845 DEBUG (pool-1-thread-1) [ALMIntegration]: https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/resources/e-Processo+%28Gerenciamento+de+Qualidade%29/testcase/testcaseRealizarloginnoeProcessoJava
14:46:14,846 DEBUG (pool-1-thread-1) [ALMIntegration]: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:testcase xmlns:ns2="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:ns4="http://jazz.net/xmlns/alm/qm/v0.1/" xmlns:ns3="http://jazz.net/xmlns/alm/v0.1/" xmlns:ns5="http://purl.org/dc/elements/1.1/">
    <ns5:title>Realizar login no e-Processo Java</ns5:title>
    <ns4:weight>100</ns4:weight>
    <ns4:priority ns4:resource="https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/process-info/_EX3W1K3iEeKZTtTZfLxNXw/priority/literal.priority.101">literal.priority.101</ns4:priority>
    <ns4:suspect>false</ns4:suspect>
    <com.ibm.rqm.planning.editor.section.testCaseDesign extensionDisplayName="RQM-KEY-TC-DESIGN-TITLE">&lt;br/&gt;Dado que vou para a tela &amp;#34;Login Java&amp;#34;</com.ibm.rqm.planning.editor.section.testCaseDesign>
</ns4:testcase>

14:46:15,247 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:119)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:220)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:181)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:262)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:159)
	... 13 more

**Comment by rogernobre** [comment]
Depois de muita luta, o erro era com em relação do nome da área do projeto.

Estava passando o nome errado.

Se o erro ocorrer com alguém favor consultar a url "https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/projects".

**Comment by kellycfs** [comment]
Estou com esse mesmo problema. Tentei os nomes da área de projeto utilizando a sugestão do @rogernobre mas o erro continua.

Versão 1.4.0 do DBehave e utilizando a propriedade behave.integration.alm.autoAssociateTestCaseInPlan=false.

16:46:43,456 ERROR (pool-1-thread-1) [ALMStoryReport]: Erro no envio de dados para integração
br.gov.frameworkdemoiselle.behave.exception.BehaveException: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:252)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.report.ALMStoryReport.afterStory(ALMStoryReport.java:103)
	at org.jbehave.core.reporters.DelegatingStoryReporter.afterStory(DelegatingStoryReporter.java:49)
	at org.jbehave.core.reporters.ConcurrentStoryReporter.afterStory(ConcurrentStoryReporter.java:125)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:324)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro ao criar caso de testes. Detalhes: HTTP/1.1 400 Bad Request 
	at br.gov.frameworkdemoiselle.behave.integration.alm.ALMIntegration.sendScenario(ALMIntegration.java:158)
	... 13 more

**Comment by juliancesar** [comment]
Favor seguir as orientações para encontrar o Alias da área de projeto no seguinte endereço da Intranet do Serpro.

http://portal.alm.serpro.gov.br/mentores-de-ferramentas/copy4_of_rqm/obter-o-servidor-do-alm-e-o-alias-do-projeto

Caso não consiga avançar favor retornar.

**Comment by kellycfs** [comment]
Olá, consegui resolver usando o link que me passou. Obrigada @juliancesar.
