### ISSUE TITLE
'textVisible' não encontra 'button' com esse 'value' igual ao texto informado

### ISSUE THREAD

**Issue by mestihudson** [demoiselle/behave#312]
Senhores, tenho a seguinte situação:
[1] um passo com as seguintes chamadas
```java
@Then("eu vejo a tela de confirmação")
public void thenEuVejoATelaDeConfirmação() {
  textVisible("Fazer Nova Comunicação");
  textVisible("Encerrar Comunicações");
}
```
[2] uma página html com o seguinte trecho, de onde espero validar as chamadas de [1]
```html
<input type="button" onclick="window.location = 'EnviarComunicacao.asp'" value="Fazer Nova Comunicação" name="voltar" class="button1">
<input type="button" onclick="window.location = 'menuopcoes.asp'" value="Encerrar Comunicações" name="encerrar" class="button1">
```
[3] no entanto, quando executo a seguinte mensagem é apresentada:
```
Failed to run story stories/comunicacao.storyConverted
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy17.waitText(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.textVisible(CommonSteps.java:287)
	at br.gov.serpro.webcoaf.steps.ComunicacaoSteps.thenEuVejoATelaDeConfirmação(ComunicacaoSteps.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:443)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
	... 20 more
Caused by: java.lang.AssertionError: Texto [Fazer Nova Comunicação] não encontrado na tela
	at org.junit.Assert.fail(Assert.java:91)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitVisibleText(WebBase.java:487)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitText(WebBase.java:407)
	... 25 more
```
Alguma dica para fazer isso funcionar, ou uma sugestão para validar a página da screenshot:
![failed-scenario-9f94bad6-7beb-472f-99d2-aa6d1585dbc6](https://cloud.githubusercontent.com/assets/687967/6507044/1de3c11a-c32e-11e4-9181-a449831fc485.png)

Obrigado, desde já.

**Comment by juliancesar** [comment]
@mestihudson, a aplicação utiliza frames ou iframes?

**Comment by mestihudson** [comment]
@juliancesar, não.

**Comment by juliancesar** [comment]
Verifique 2 coisas: 1 - Existe uma tag body no HTML e  2 - se existe somente 1 ou mais de uma.

Pergunto isso pois os 2 casos já aconteceram!

**Comment by juliancesar** [comment]
@mestihudson, acredito ter encontrado o problema!

Na frase de verificar o texto na tela utilizamos o método getText do Webdriver que diz o seguinte:

```java
 /**
   * Get the visible (i.e. not hidden by CSS) innerText of this element, including sub-elements,
   * without any leading or trailing whitespace.
   * 
   * @return The innerText of this element.
   */
  String getText();
```

Neste caso temos 2 alternativas:
1 - Alterar para ***driver.getPageSource()*** e procurar dentro do código inteiro da página/frame
2 - ou criar uma nova frase somente para isso

@mestihudson, @rogernobre e @arildojg, qual é a opinião de vocês?

**Comment by mestihudson** [comment]
@juliancesar, como o texto procurado encontra-se dentro de um atributo de uma tag, acredito que realmente faz sentido que o mesmo não seja encontrado. Também acho que é um caso muito específico, e que uma nova frase talvez não agregue muito valor. Ainda considero que utilizar o `getPageSource` voltaríamos a uma situação anterior que já foi solucionada (o busca em texto que não está atualmente visível).
Sendo assim, vou fazer a verificação pela existência do elemento, para o momento, mas fico no aguardo por sugestões mais elegantes.
Obrigado.

**Comment by rogernobre** [comment]
@mestihudson, só mudar o método se os botões forem mapeados. Nessa situação, seria verificar a visibilidade de componentes que identifiquem a tela

**Comment by rogernobre** [comment]
Se fosse link, entrariam no texto da tela. Como são botões não entram.

**Comment by mestihudson** [comment]
Se eu entendi o que você falou, @rogernobre, seria fazer algo do tipo:
```java
@Then("eu vejo a tela de confirmação")
public void thenEuVejoATelaDeConfirmação() {
  pageWithName("Registrar Comunicação - Resultado");
  elementVisibleClicableEnable("Fazer Nova Comunicação");
  elementVisibleClicableEnable("Encerrar Comunicações");
}
```
E, repensando minha resposta, talvez uma frase/método como o abaixo ilustrado, não seria uma má ideia:
```gherkin
Então verifico a presença de "$elemento"
```

**Comment by juliancesar** [comment]
@mestihudson, talvez no lugar de usar a frase:

```gherkin
Então verifico a presença de "$elemento"
```

você possa usar a que já existe no dbehave:

```gherkin
aguardo o elemento "$fieldName" estar visível, clicável e habilitado
```

será que ajuda?

**Comment by rogernobre** [comment]
@mestihudson, isso mesmo.

No projeto em que estou, eu sobrescrevo o pageWithName para validar a url ou titulo da pagina atual, verificando com a página mapeada (o titulo tem validação parcial do nome da tela na historia).

**Comment by mestihudson** [comment]
@juliancesar e @rogernobre, perfeito. Acho que é o método mapeado por esta frase que estou utilizando.
Obrigado.

**Comment by juliancesar** [comment]
@mestihudson, podemos fechar esta issue ou você ainda tem mais alguma consideração?

**Comment by mestihudson** [comment]
Não, por mim está fechado.
