### ISSUE TITLE
Erro no projeto exemplo "treino" na versão 1.4.4-SNAPSHOT

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#337]
Erro no projeto exemplo "treino" na versão 1.4.4-SNAPSHOT:
...
Quando informo "Ação" no campo "Seleção de Opção 1"
Então será exibido na "Seleção de Opção 1" o valor "Ação" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
...
Failed to run story stories/components/components.storyConverted
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy17.waitTextInElement(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.textVisibleInElement(CommonSteps.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:443)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
	... 20 more
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Erro Inesperado, Unable to locate element: {"method":"tag name","selector":"select"}
Command duration or timeout: 15.10 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'serpro-1541809', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.2.0-58-generic-pae', java.version: '1.6.0_45'
*** Element info: {Using=tag name, value=select}
Session ID: 00b43124-a152-4aa1-9a92-bdb30f82a0d3
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, rotatable=false, locationContextEnabled=true, version=24.8.0, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=true, takesScreenshot=true}]
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitTextInElement(WebBase.java:620)
	... 25 more
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"tag name","selector":"select"}
Command duration or timeout: 15.10 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'serpro-1541809', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.2.0-58-generic-pae', java.version: '1.6.0_45'
*** Element info: {Using=tag name, value=select}
Session ID: 00b43124-a152-4aa1-9a92-bdb30f82a0d3
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, rotatable=false, locationContextEnabled=true, version=24.8.0, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=true, webStorageEnabled=true, applicationCacheEnabled=true, takesScreenshot=true}]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:268)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:171)
	at org.openqa.selenium.remote.RemoteWebElement.findElementByTagName(RemoteWebElement.java:260)
	at org.openqa.selenium.By$ByTagName.findElement(By.java:330)
	at org.openqa.selenium.remote.RemoteWebElement.findElement(RemoteWebElement.java:167)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebSelect.getText(WebSelect.java:95)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitTextInElement(WebBase.java:604)
	... 25 more
Caused by: org.openqa.selenium.NoSuchElementException: Unable to locate element: {"method":"tag name","selector":"select"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
System info: host: 'serpro-1541809', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'i386', os.version: '3.2.0-58-generic-pae', java.version: '1.6.0_45'
Driver info: driver.version: unknown
	at <anonymous class>.FirefoxDriver.prototype.findElementInternal_(file:///tmp/anonymous3579407167213700024webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:10271)
	at <anonymous class>.fxdriver.Timer.prototype.setTimeout/<.notify(file:///tmp/anonymous3579407167213700024webdriver-profile/extensions/fxdriver@googlecode.com/components/driver-component.js:603)

**Comment by juliancesar** [comment]
Favor testar novamente com essa correção.
Obrigado pela colaboração.

**Comment by rogernobre** [comment]
@juliancesar, tudo ok.
