### ISSUE TITLE
Erro no projeto exemplo "sample-google" na versão 1.4.4-SNAPSHOT

### ISSUE THREAD

**Issue by rogernobre** [demoiselle/behave#338]
Erro no projeto exemplo "sample-google" na versão 1.4.4-SNAPSHOT:

O mapeamento do componente "Logotipo" na tela "Tela de Busca" não existe:
...
Running story stories/estou-com-sorte.storyConverted
Funcionalidade: pedido
(stories/estou-com-sorte.storyConverted)
Narrative:
In order to algo interessante seja buscado
As a visitante
I want to clicar em um botão
Scenario: Utilização da funcionalidade estou com sorte
Dado que vou para a tela "Tela de Busca"
18:52:41,901 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [https://www.google.com.br/?gws_rd=ssl] salvo em [/home/01069360503/workspace/dbehave/behave/sample/search-google/target/jbehave/view/screenshots/failed-scenario-105593dc-5252-49b1-bb0e-dd2433c8c116.png] com [90.539] bytes
Então aguardo o elemento "Logotipo" referente a "Google" estar visível, clicável e habilitado (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
Então aguardo o elemento "Campo de Busca" estar visível, clicável e habilitado (NOT PERFORMED)
Então aguardo o elemento "Estou com sorte" estar visível, clicável e habilitado (NOT PERFORMED)
Quando clico em "Estou com sorte" (NOT PERFORMED)
Então será exibido "Sobre" (NOT PERFORMED)
...
Failed to run story stories/estou-com-sorte.storyConverted
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy13.waitVisibleClickableEnabled(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.elementWithParametersVisibleClicableEnable(CommonSteps.java:330)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$ParameterisedStep.perform(StepCreator.java:550)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runScenarioSteps(StoryRunner.java:443)
	at org.jbehave.core.embedder.StoryRunner.runCancellable(StoryRunner.java:305)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:219)
	at org.jbehave.core.embedder.StoryRunner.run(StoryRunner.java:180)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:229)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:201)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
	... 20 more
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Elemento [Logotipo] não encontrado na página
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.findFrameContainingElement(WebBase.java:316)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitClickable(WebBase.java:367)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebBase.waitVisibleClickableEnabled(WebBase.java:361)
	... 25 more

**Comment by rogernobre** [comment]
Proposta de alteração para corrigir o erro:

https://github.com/demoiselle/behave/pull/339
