### ISSUE TITLE
O behave não insere a url no browser 

### ISSUE THREAD

**Issue by WillyPess** [demoiselle/behave#343]
O browser abre normal , mas não insere a URL (Behave versão : 1.4.3 ; Firefox : 24.8.0)

org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

(process:5052): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
*** LOG addons.xpi: startup
*** LOG addons.xpi: Ignoring file entry whose name is not a valid add-on ID: /tmp/anonymous1350593863818578831webdriver-profile/extensions/webdriver-staging
*** LOG addons.xpi: checkForChanges
*** LOG addons.xpi: No changes found

	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.start(NewProfileExtensionConnection.java:95)
	at org.openqa.selenium.firefox.FirefoxDriver.startClient(FirefoxDriver.java:187)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:93)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:142)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:88)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.util.WebBrowser$2.getWebDriver(WebBrowser.java:110)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.WebDriverRunner.getDriver(WebDriverRunner.java:83)
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.WebDriverRunner.start(WebDriverRunner.java:100)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.startStories(BeforeAfterSteps.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$MethodInvoker.invoke(StepCreator.java:671)
	at org.jbehave.core.steps.StepCreator$BeforeOrAfterStep.perform(StepCreator.java:458)
	at org.jbehave.core.embedder.StoryRunner$FineSoFar.run(StoryRunner.java:499)
	at org.jbehave.core.embedder.StoryRunner.runStepsWhileKeepingState(StoryRunner.java:479)
	at org.jbehave.core.embedder.StoryRunner.runBeforeOrAfterStories(StoryRunner.java:79)
	at org.jbehave.core.embedder.StoryManager.runBeforeOrAfterStories(StoryManager.java:91)
	at org.jbehave.core.embedder.StoryManager.runStories(StoryManager.java:75)
	at org.jbehave.core.embedder.Embedder.runStoriesAsPaths(Embedder.java:202)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.JBehaveParser.run(JBehaveParser.java:152)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:158)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:186)
	at br.gov.serpro.sigepe.ad.demoisellebehave.ConcluirPlanoTrabalho.CadastrarTipoGrupoFunctionalTest.ConcluirPlanoTrabalhoFB(CadastrarTipoGrupoFunctionalTest.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)

**Comment by juliancesar** [comment]
Você esta rodando local ou remoto? Tente utilizar a versão **1.4.4**.

**Comment by WillyPess** [comment]
Local

**Comment by WillyPess** [comment]
versão 1.4.4 , tambem não funcionou..

**Comment by juliancesar** [comment]
Este problema é comum estar relacionado a incompatibilidade entre a versão do WebDriver (Selenium) e a versão do Firefox.
Faça um teste para mim, crie um projeto do zero utilizando o arquétipo **jbehave-selenium-archetype** e verifique se funciona, aguardo o seu retorno.

**Comment by juliancesar** [comment]
@WillyPess, algum retorno sobre o assunto?

**Comment by WillyPess** [comment]
Desculpe , não tinha visto sua resposta , vou fazer o teste e volto com o resultado

**Comment by WillyPess** [comment]
Com o projeto criado do zero , funcionou normalmente , o que pode ser ?

**Comment by juliancesar** [comment]
Esta tudo indicando a questão da compatibilidade entre o Firefox e o WebDriver, manda para nós o seu **behave.properties**.

**Comment by WillyPess** [comment]
behave.runner.screen.maxWait=49900
behave.runner.screen.minWait=3900
behave.integration.alm.enabled=false
behave.integration.alm.url.security=https://alm.serpro/qm/j_security_check/
behave.integration.alm.url.services=https://alm.serpro/qm/service/com.ibm.rqm.integration.service.IIntegrationService/
behave.integration.alm.projectArea=SIGEPE - Avaliação de Desempenho (Gerenciamento de Qualidade)_2
behave.integration.alm.testPlanId=2011
behave.integration.authenticator.port=9992
behave.integration.authenticator.host=localhost

**Comment by juliancesar** [comment]
Aparentemente o seu arquivo properties esta correto. 
Quando você criou o projeto do zero, qual foi a versão que você usou?

**Comment by WillyPess** [comment]
A mesma versão do outro (Behave versão : 1.4.3 ; Firefox : 24.8.0) , porém o que eu percebi é que a versão do Selenium do projeto criado do zero é 2.45.0 , e o do projeto que eu criei é 2.20 , será isso?

**Comment by juliancesar** [comment]
Muito provável! Essa situação é incomum, pois alguma outra biblioteca do seu projeto deve estar com esta versão bem antiga do Selenium!

Tente forçar no seu projeto a utilização do **2.45.0** adicionando as seguinte tags no seu pom:

```xml
<dependency>
	<groupId>org.seleniumhq.selenium</groupId>
	<artifactId>selenium-java</artifactId>
	<version>2.45.0</version>
</dependency>
```

**Comment by WillyPess** [comment]
Ok , obrigado pela ajuda , vou tentar fazer esse teste

**Comment by juliancesar** [comment]
@WillyPess , vou fechar esta issue, e caso ainda tenha problemas pode reabrir ela.
