### ISSUE TITLE
NoSuchMethodError EmbedderControls.useStoryTimeouts

### ISSUE THREAD

**Issue by mestihudson** [demoiselle/behave#371]
```
java.lang.NoSuchMethodError: org.jbehave.core.embedder.EmbedderControls.useStoryTimeouts(Ljava/lang/String;)Lorg/jbehave/core/embedder/EmbedderControls;
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.JBehaveParser.run(JBehaveParser.java:138)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:156)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:184)
	at br.gov.serpro.sinesp.cadastros.test.e2e.DoneETest.stories(DoneETest.java:44)
```
Aparentemente, o método não existe mais.
Verificando, parece que foi substituido por `useStoryTimeoutInSecs`.

**Comment by juliancesar** [comment]
Sim, na versão *1.5.1* subimos a versão do JBehave para a 4.0.1 que possui esta alteração.

Mais informações: 
* http://jbehave.org/reference/stable/release-notes.html
* commit: https://github.com/demoiselle/behave/commit/cc3d4e1de8f128d7e519381b4045f3e61b594a97#diff-97158c400fb3073fc3f56b3edca47c44L118

**Comment by mestihudson** [comment]
Nesse caso, é preciso fazer o downgrade? Como resolvo?

**Comment by mestihudson** [comment]
Resolvido.
