### ISSUE TITLE
Falha na execução dos testes

### ISSUE THREAD

**Issue by trsilva** [demoiselle/behave#373]
Bom dia!

Estou com problemas para executar os testes de exemplo e do projeto de treinamento do DBehave em uma máquina fora do Brasil. Suponho ser algum erro relacionado às opções de regionalização do Java. Segue abaixo o trace:

java.lang.ExceptionInInitializerError
    at br.gov.frameworkdemoiselle.behave.config.BehaveConfig.<clinit>(BehaveConfig.java:71)
    at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<init>(BehaveContext.java:88)
    at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<clinit>(BehaveContext.java:63)
    at br.gov.serpro.behave.projeto01.EstoqueTest.<init>(EstoqueTest.java:12)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
    at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
    at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.util.MissingResourceException: Can't find bundle for base name demoiselle-behave-core-bundle, locale fr_FR
    at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1499)
    at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1322)
    at java.util.ResourceBundle.getBundle(ResourceBundle.java:795)
    at br.gov.frameworkdemoiselle.behave.message.BehaveMessage.<init>(BehaveMessage.java:62)
    at br.gov.frameworkdemoiselle.behave.internal.util.PropertiesLoaderUtil.<clinit>(PropertiesLoaderUtil.java:65)
    ... 26 more

Segui todas as instruções de instalação do manual e não consegui rodar sequer os exemplos. Alguma solução?!

**Comment by juliancesar** [comment]
Foi criada uma correção que pode resolver o problema.

Neste momento esta sendo gerada uma nova SNAPSHOT com nome **1.5.2-SNAPSHOT**. O processo demora em média 2 horas para ser concluído, então a partir das 10h (Brasília) basta alterar o seu pom.xml para a versão 1.5.2-SNAPSHOT e rodar novamente.

Caso o problema tenha sido resolvido favor fechar a issue.

**Comment by juliancesar** [comment]
@trsilva, conseguiu testar?

**Comment by trsilva** [comment]
Julian, muito obrigado pelo retorno!

Consegui rodar a versão 1.5.1 com aquela alteração do SO. Vou testar esse SNAPSHOT e dou um retorno aqui!

Abraços.

**Comment by trsilva** [comment]
Julian,
finalmente consegui testar esse SNAPSHOT. Me desculpe pela demora!

O erro no Locale aparentemente foi resolvido, porém agora temos um NullPointerException. :-)

**Comment by juliancesar** [comment]
Mande a stack trace.

**Comment by trsilva** [comment]
java.lang.ExceptionInInitializerError
	at br.gov.frameworkdemoiselle.behave.config.BehaveConfig.<clinit>(BehaveConfig.java:71)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<init>(BehaveContext.java:88)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<clinit>(BehaveContext.java:63)
	at br.gov.serpro.behave.casestudy.MyTest.<init>(MyTest.java:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at br.gov.frameworkdemoiselle.behave.config.BehaveConfig.getProperty(BehaveConfig.java:88)
	at br.gov.frameworkdemoiselle.behave.message.BehaveMessage.<init>(BehaveMessage.java:66)
	at br.gov.frameworkdemoiselle.behave.internal.util.PropertiesLoaderUtil.<clinit>(PropertiesLoaderUtil.java:65)
	... 26 more

**Comment by juliancesar** [comment]
Qual é o valor da propriedade **behave.message.locale** que está selecionado no arquivo behave.properties?

**Comment by trsilva** [comment]
Essa propriedade não está disponível no behave.properties, Julian.

**Comment by juliancesar** [comment]
@trsilva, você ainda continua com o problema? 

Favor testar a versão **1.5.2-SNAPSHOT**, pois foram feitas algumas modificações relacionadas ao seu problema.

**Comment by trsilva** [comment]
Julian,

o erro é aparentemente o mesmo:

java.lang.ExceptionInInitializerError
	at br.gov.frameworkdemoiselle.behave.config.BehaveConfig.<clinit>(BehaveConfig.java:71)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<init>(BehaveContext.java:88)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.<clinit>(BehaveContext.java:63)
	at br.gov.serpro.behave.projeto03.tests.AcessoTests.<init>(AcessoTests.java:9)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:202)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:251)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:248)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.NullPointerException
	at br.gov.frameworkdemoiselle.behave.config.BehaveConfig.getProperty(BehaveConfig.java:88)
	at br.gov.frameworkdemoiselle.behave.message.BehaveMessage.<init>(BehaveMessage.java:66)
	at br.gov.frameworkdemoiselle.behave.internal.util.PropertiesLoaderUtil.<clinit>(PropertiesLoaderUtil.java:65)
	... 26 more

**Comment by juliancesar** [comment]
@trsilva, coloque em modo debug o projeto (https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/resources/log4j.xml#L24) e nos mande o início do teste em que ele mostra todas as propriedades do teste.

**Comment by trsilva** [comment]
Bom dia, Julian!

Não entendi exatamente o que você gostaria que fosse feito!

**Comment by juliancesar** [comment]
Se não existir crie o arquivo **src/test/resources/log4j.xm** e adicione o conteúdo do arquivo https://github.com/demoiselle/behave/blob/master/sample/mix/src/test/resources/log4j.xml#L24. 
Após fazer isso rode os testes e o log ficará com mais informações.

O objetivo é colocar o dbehave em modo de **debug** para que eu possa ver o valor das suas propriedades em tempo de execução.

**Comment by trsilva** [comment]
Julian,

o log que você precisa é o que normalmente é exibido no Console? Porque os testes não chegam a rodar pra que este seja gerado. O Failure Trace do JUnit mostra um java.lang.ExceptionInInitializerError, com o NullPointerException mencionado acima.

**Comment by ttperes** [comment]
@juliancesar @trsilva pessoal acredito que consegui realizar a correção do problema. Vou realizar o pull e quando sair na versão nova por favor testem.

**Comment by juliancesar** [comment]
Vou fechar esta issue pois acredito que ela tenha sido resolvida na **1.5.2-SNAPSHOT**.
Caso o problema persista favor reabrir a issue.
