### ISSUE TITLE
Em aplicações Desktop, não é possível recuperar telas que herdam de javax.swing.JScrollPane

### ISSUE THREAD

**Issue by joaquimpedrooliveira** [demoiselle/behave#379]
Ao tentar navegar para uma tela que herda de `javax.swing.JScrollPane`, ocorre `ClassCastException` no método `br.gov.frameworkdemoiselle.behave.runner.fest.FestRunner.navigateTo`, pois é feito um cast para `JPanel`, que está em outro ramo da [hierarquia do Swing/AWT](https://docs.oracle.com/javase/7/docs/api/javax/swing/package-tree.html).

Com isto, não é possível se navegar para telas que herdam desta classe.

**Comment by juliancesar** [comment]
Olá, interessante a situação, pois como pode ser visto nesta linha https://github.com/demoiselle/behave/blob/master/impl/runner/fest/src/main/java/br/gov/frameworkdemoiselle/behave/runner/fest/FestRunner.java#L149 é feita uma verificação nas linhas 152 e 167 para verificar o tipo.

Nos mande a stacktrace do erro.

**Comment by joaquimpedrooliveira** [comment]
Julian, o problema ocorre justamente na linha 154, pois o método `((JDialog) w).getRootPane().getContentPane()` retorna um `javax.swing.JScrollPane`, que não é um `JPanel`. Amanhã mando o stacktrace! :+1:

**Comment by juliancesar** [comment]
Você tem alguma sugestão de código que corrija o problema?

**Comment by joaquimpedrooliveira** [comment]
Julian, segue o stacktrace:

`org.jbehave.core.embedder.PerformableTree$SomethingHappened@1de06ec: java.lang.ClassCastException: javax.swing.JScrollPane cannot be cast to javax.swing.JPanel
	at br.gov.frameworkdemoiselle.behave.runner.fest.FestRunner.navigateTo(FestRunner.java:154)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.goToWithName(CommonSteps.java:89)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:317)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1012)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:930)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:853)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:781)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:758)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:390)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:364)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
	at java.lang.Thread.run(Thread.java:662)`

**Comment by joaquimpedrooliveira** [comment]
Não cheguei a implementar nenhum patch nem conheço muito de Java Desktop, mas olhando o código penso que fazer o cast para `javax.swing.JComponent` em vez de `javax.swing.JPanel` deve funcionar, pois todos os métodos que você chama das linhas 155-157 são de `JComponent`.

**Comment by joaquimpedrooliveira** [comment]
Complementando: no outro local que você usa a variável `currentContainer`, no método `private void reSize(Container w, String filePath)`, você armazena como `java.awt.Container`, que é pai de `javax.swing.JComponent`. Parece que não tem maiores impactos mesmo. :-)

**Comment by juliancesar** [comment]
Acabo de publicar uma nova versão **1.5.2-SNAPSHOT** com a sua sugestão, favor testar e retornar.

**Comment by joaquimpedrooliveira** [comment]
Julian, a correção resolveu os dois casos que tínhamos no nosso projeto! Valeu!  :-)
