### ISSUE TITLE
Dúvida select com dois xpaths

### ISSUE THREAD

**Issue by estivalet** [demoiselle/behave#384]
Tenho um componente combobox do emberjs que, para funcionar com o framework, tenho que mapear dois elementos de tela: 1 div que uso para clicar e abrir o combo, e outro para selecionar a opção que desejo. Fiz assim e funcionou.

    @ElementMap(name = "país", locatorType = ElementLocatorType.Id, locator = "s2id_select__pais-endereco_fornecedor_identificacao")
     private Button dspais;

    @ElementMap(name = "selecionar país", locatorType = ElementLocatorType.XPath, locator = "//div[.='%param1%']")
     private Button prog;

Na estória eu tenho que fazer assim (2 passos):

Quando clico em "país"
Quando clico em "selecionar país" referente a "BRASIL"

Tentei refatorar para usar o select com 2 xpaths e apenas 1 passo na estória mas não funcionou.

    @ElementMap(name = "país", locatorType = ElementLocatorType.XPath, locator = { "//div[@id='s2id_select__pais-endereco_fornecedor_identificacao']", "//div[.='%param1%']" })
    private Select selectOpcao1;

Quando clico em "país" referente a "BRASIL"

Failed to run batch
org.jbehave.core.embedder.PerformableTree$SomethingHappened@e8606c: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Tipo de elemento [com.sun.proxy.$Proxy17] inválido
    at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.clickButtonWithParameters(CommonSteps.java:116)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
    at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:317)
    at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1012)
    at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:902)
    at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:930)
    at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:853)

**Comment by juliancesar** [comment]
@estivalet, você conseguiu avançar neste assunto ou ainda esta com problema?

**Comment by rogernobre** [comment]
@estivalet, o passo que você usou é somente usado para "Button", "Link", "Menu" e "MenuItem"

**Comment by rogernobre** [comment]
@estivalet, hoje a implementação para o select (WebSelect) está fixa com a tag "li"(https://github.com/demoiselle/behave/blob/master/impl/runner/webdriver/src/main/java/br/gov/frameworkdemoiselle/behave/runner/webdriver/ui/WebSelect.java). Se alguém tiver tempo disponível para alterar essa classe para permitir o clique usando o segundo Xpath (e não fixar a tag "li"), o passo que funcionaria seria: Quando informo "Brasil" no campo "país". E o mapeamento seria o mesmo que você apresentou acima: @ElementMap(name = "país", locatorType = ElementLocatorType.XPath, locator = { "//div[@id='s2id_select__pais-endereco_fornecedor_identificacao']", "//div[.='%param1%']" })
private Select selectOpcao1;

**Comment by ttperes** [comment]
Eu tenho um só que focado em primefaces que você usa somente 1 xpath e 1 frase. Achei a solução com dois xpaths estranha. Só que não publiquei pois fiz somente o básico da funcionalidade para os meus projetos (pego somente por string, não implementei por id, value etc).

**Comment by juliancesar** [comment]
Vou fechar esta issue, caso julguem necessário podem reabri-la.
