### ISSUE TITLE
Configurar projeto de Testes Automatizados (Dbhave) no ambiente de Integração Contínua - IC

### ISSUE THREAD

**Issue by cesarfex** [demoiselle/behave#462]
Solicito ajuda para configurar projeto de Testes Automatizados (Dbhave) no ambiente de Integração Contínua , e buscar paralelizar sua execução em parceria com um dos membros do time,  de acordo com as necessidades do projeto (atualmente é muito demorado) .  O projeto é Java com Demoiselle 2 e já tem um job no jenkins corporativo configurado para execução dos testes.

/label ~duvida

**Comment by juliancesar** [comment]
Bom dia, as issues criadas no GitHub não tem previsão de entrega e priorização, portanto caso a demanda necessite é preciso abrir uma Solicitação na ALM na área Gestão SUPSD com assunto Demoiselle Behave.

**Comment by cesarfex** [comment]
Oi @juliancesar!  Grato pelo retorno, neste caso não necessita de priorização.

Atualmente temos um ambiente no (AmbDes) dedicado para execução de testes, porém, estes ambientes não possuem interface gráfica que impedem o acionamento de navegadores.

Para isso, temos o job XXXXXX-BDD já está configurado no JenkinsCorporativo, na parte de "Ambiente de Build" marcado a opção para usar o **XVFB**. Esse Job é responsável por baixar, compilar e testar o código-fonte que está versionado no RTC (ALM) e publicar o artefato (WAR) no JBoss no Portal de Desenvolvimento (AmbDes)**

O problema é que a goal mvn roda normalmente na minha estação pois, tenho o navegador e conforme stacktrace abaixo ao tentar iniciar o navegador no jenkins está apresentando o erro abaixo: Lofg completo em anexo
[log-job-bdd-jenkins.txt](https://github.com/demoiselle/behave/files/962098/log-job-bdd-jenkins.txt)

```java
15:57:02,398 INFO  (main) [BeforeAfterSteps]: >>Iniciando Aplicação<<
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0","maxVersion":"45.*"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1493233024661	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1493233024662	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"3s64bdrkqY2h","location":"app-global","version":"45.5.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1479511480000,"updateDate":1479511480000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.5.0","maxVersion":"45.5.0"}],"targetPlatforms":[],"seen":true}
1493233024663	addons.xpi	DEBUG	getModTime: Recursive scan of {972ce4c6-7e08-4474-a285-3208198ce6fd}

ERROR (main) [ScreenShootingMaker]: org.openqa.selenium.WebDriverException: Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 
":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0","maxVersion":"45.*"},

Firefox console output:
":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.0","maxVersion":"45.*"},{"id":"xpcshell@tests.mozilla.org","minVersion":"0","maxVersion":"10"}],"targetPlatforms":[],"multiprocessCompatible":false,"seen":true}
1493233069321	addons.xpi	DEBUG	getModTime: Recursive scan of loop@mozilla.org
1493233069322	addons.xpi	DEBUG	Updating XPIState for {"id":"{972ce4c6-7e08-4474-a285-3208198ce6fd}","syncGUID":"psAuhqCQAkRM","location":"app-global","version":"45.5.0","type":"theme","internalName":"classic/1.0","updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"icons":{"32":"icon.png","48":"icon.png"},"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Default","description":"The default theme.","creator":"Mozilla","homepageURL":null,"contributors":["Mozilla Contributors"]},"visible":true,"active":true,"userDisabled":false,"appDisabled":false,"descriptor":"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi","installDate":1479511480000,"updateDate":1479511480000,"applyBackgroundUpdates":1,"skinnable":true,"size":5028,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"strictCompatibility":true,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"45.5.0","maxVersion":"45.5.0"}],"targetPlatforms":[],"seen":true}


ERROR (main) [ScreenShootingMaker]: Erro ao salvar screenshot [] caminho [/opt/programas/jenkins/workspace/DESDR/DE502/SISCOAF/SISCOAF-BDD/siscoaf/01-Sistema/05-Implementacao/01-Aplicacao/siscoaf/siscoaf-bdd/target/jbehave/view/screenshots/failed-scenario-aca0f59b-45fc-4ec1-8eb0-5f7125d9591c.png] causa [Failed to connect to binary FirefoxBinary(/usr/bin/firefox) on port 7055; process output follows: 


Failures in reports view: 9 scenarios failed
16:06:09,460 INFO  (main) [JBehaveParser]: Finalizando Parser JBehave...
16:06:09,460 INFO  (main) [BehaveContext]: --------------------------------
16:06:09,460 INFO  (main) [BehaveContext]: Demoiselle Behave Finalizado
16:06:09,460 INFO  (main) [BehaveContext]: --------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 555.42 sec <<< FAILURE! - in br.gov.fazenda.coaf.siscoaf.SiscoafTest
testIntranetStoriesLogin(br.gov.fazenda.coaf.siscoaf.SiscoafTest)  Time elapsed: 555.373 sec  <<< FAILURE!
java.lang.AssertionError: Passo com falha: [br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps.stopStories()] causa: org.jbehave.core.failures.BeforeOrAfterFailed: Method stopStories (annotated with @AfterStories in class br.gov.frameworkdemoiselle.behave.parser.jbehave.BeforeAfterSteps) failed: java.lang.NullPointerException
	at org.junit.Assert.fail(Assert.java:91)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:158)
	at br.gov.frameworkdemoiselle.behave.controller.BehaveContext.run(BehaveContext.java:184)
	at br.gov.fazenda.coaf.siscoaf.SiscoafTest.testIntranetStoriesLogin(SiscoafTest.java:65)
```

**Comment by cesarfex** [comment]
@juliancesar Separe um tempinho para eu te apresentar nosso pipeline e vermos essa questão... acredito que seja uma besteira que estou fazendo errado e que apenas em 30 minutos no máximo resolveremos.
Que dia fica bom para você?

**Comment by juliancesar** [comment]
Esta bem complicado para mim, me ligue ainda hoje e tentamos resolver isso.

**Comment by juliancesar** [comment]
@cesarfex, você conseguiu fechar o assunto?

**Comment by juliancesar** [comment]
Issue concluída, caso ainda tenha problemas favor reabrir.
