### ISSUE TITLE
Problema no preenchimento de uma caixa de texto em uma aplicação Angular

### ISSUE THREAD

**Issue by alineas** [demoiselle/behave#491]
Na automação de testes funcionais de uma aplicação desenvolvida em Angular com o Demoiselle Behave, mapeei uma caixa de texto (TextField) com id da seguinte forma:

@ElementMap(name = "Número da Inscrição", locatorType = ElementLocatorType.Id, locator = "inscricao")
private TextField txtNumeroInscricão;

Porém, durante a execução dos testes automatizados, o cursor fica piscando entre tal caixa de texto e a que está abaixo dela e tal campo não é preenchido até que é lançada a exceção abaixo:

Running story stories/devedores/buscadevedores.storyConverted
Funcionalidade: Busca de Devedores do Sistema Analytics
(stories/devedores/buscadevedores.storyConverted)
Narrative:
In order to lista de Devedores
As a usuário
I want to ter acesso à funcionalidade Busca de Devedores
Scenario: CT - Acessar Busca de Devedores
Using timeout for story buscadevedores.storyConverted of 21600 secs.
Dado que vou para a tela "Tela de Login"
Quando informo "28731484115" no campo "Usuário"
Quando informo "batata10" no campo "Senha"
Quando informo "a" no campo "Captcha"
Quando clico em "Login"
Então será exibido "IP"
Dado que estou na tela "Principal"
Quando clico em "Menu"
Quando movo o mouse sobre "Devedores"
Quando clico em "Busca Devedores"
Dado que estou na tela "Busca de Devedores"
Então será exibido "Selecione o parâmetro de pesquisa desejado:"
14:32:41,329 INFO  (pool-1-thread-1) [ScreenShootingMaker]: Screenshot [https://10.139.7.107/busca/busca-devedores2] salvo em [/home/96957697304/workspace analytics/administracao/06-Teste/05-Scripts/automacao/testsanalytics/target/jbehave/view/screenshots/failed-scenario-7894529c-8274-47d8-8c78-b3679a326525.png] com [32.636] bytes
Quando informo "2040400000156" no campo "Número da Inscrição" (FAILED)
(java.lang.reflect.UndeclaredThrowableException)
Quando clico em "Consultar" (NOT PERFORMED)
Então será exibido "Parâmetro de pesquisa atual > CPF/CNPJ > 28731484115" (NOT PERFORMED)

(AfterStories)
14:32:41,585 INFO  (main) [BeforeAfterSteps]: >>Finalizando Aplicação<<

Failed to run batch 
org.jbehave.core.embedder.PerformableTree$SomethingHappened@57352cf2: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy13.sendKeysWithTries(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.parser.jbehave.CommonSteps.inform(CommonSteps.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:598)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:317)
	at org.jbehave.core.embedder.PerformableTree$PerformableSteps.perform(PerformableTree.java:1012)
	at org.jbehave.core.embedder.PerformableTree$AbstractPerformableScenario.performRestartableSteps(PerformableTree.java:902)
	at org.jbehave.core.embedder.PerformableTree$NormalPerformableScenario.perform(PerformableTree.java:930)
	at org.jbehave.core.embedder.PerformableTree$PerformableScenario.perform(PerformableTree.java:853)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.performScenarios(PerformableTree.java:781)
	at org.jbehave.core.embedder.PerformableTree$PerformableStory.perform(PerformableTree.java:758)
	at org.jbehave.core.embedder.PerformableTree.performCancellable(PerformableTree.java:390)
	at org.jbehave.core.embedder.PerformableTree.perform(PerformableTree.java:364)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:291)
	at org.jbehave.core.embedder.StoryManager$EnqueuedStory.call(StoryManager.java:265)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at br.gov.frameworkdemoiselle.behave.internal.ui.UIProxy.invoke(UIProxy.java:35)
	... 22 more
Caused by: br.gov.frameworkdemoiselle.behave.exception.BehaveException: Limpeza de campo não concluída com sucesso
	at br.gov.frameworkdemoiselle.behave.runner.webdriver.ui.WebTextField.sendKeysWithTries(WebTextField.java:95)
	... 27 more

Generating reports view to '/home/96957697304/workspace analytics/administracao/06-Teste/05-Scripts/automacao/testsanalytics/target/jbehave' using formats '[defaultstoryreport, console, html, stats, xml]' and view properties '{navigator=ftl/jbehave-navigator.ftl, views=ftl/jbehave-views.ftl, reports=ftl/jbehave-reports.ftl, nonDecorated=ftl/jbehave-report-non-decorated.ftl, decorated=ftl/jbehave-report-decorated.ftl, maps=ftl/jbehave-maps.ftl}'
Reports view generated with 2 stories (of which 0 pending) containing 1 scenarios (of which 0 pending)
Failures in reports view: 1 scenarios failed
14:32:41,879 INFO  (main) [JBehaveParser]: Finalizando Parser JBehave...
14:32:41,879 INFO  (main) [BehaveContext]: --------------------------------
14:32:41,881 INFO  (main) [BehaveContext]: Demoiselle Behave Finalizado
14:32:41,881 INFO  (main) [BehaveContext]: --------------------------------

Os testes foram executados no Firefox 52.6.0 tanto com a versão 1.5.3 quanto com a versão 1.6.0-BETA2 do Demoiselle Behave e o problema apresentado foi o mesmo.

Url da aplicação: https://10.139.7.107/login
Funcionalidade em testes: Menu -> Devedores -> Busca Devedores

**Comment by alineas** [comment]
O problema foi resolvido com a inclusão do passo particular abaixo no projeto:

@When("informo o texto \"$text\" em \"$elementName\"")
 public void informText(String text, String elementName) {
          WebElement webElement = getWebElement(runner, currentPageName, elementName);
          webElement.clear();
          webElement.sendKeys(text);
}

Dessa forma, para o preenchimento dos campos em questão utilizei o passom conforme o exemplo a seguir:

Quando informo o texto "123.456.789-09" em "Número do CPF/CNPJ Base"
